"""Synthesis agent for creating final reports."""

import json
from datetime import datetime
from typing import Optional

from .base import BaseAgent, AgentOutput


class SynthesisAgent(BaseAgent):
    """Agent that synthesizes all findings into a coherent report."""
    
    name = "synthesis"
    description = "Combines all research findings into a comprehensive report"
    
    def run(self, task: str, context: dict = None) -> AgentOutput:
        """Synthesize findings into a final report."""
        try:
            # Generate the final report
            report = self._generate_report(task, context)
            
            # Collect all sources
            all_sources = []
            if context:
                for key, value in context.items():
                    if isinstance(value, dict) and "sources" in value:
                        all_sources.extend(value["sources"])
                    elif isinstance(value, AgentOutput):
                        all_sources.extend(value.sources)
            
            return AgentOutput(
                agent_name=self.name,
                content=report,
                sources=list(set(all_sources)),
                success=True
            )
        
        except Exception as e:
            return AgentOutput(
                agent_name=self.name,
                content=f"Synthesis failed: {str(e)}",
                success=False,
                error=str(e)
            )
    
    def _generate_report(self, task: str, context: dict = None) -> str:
        """Generate the final research report."""
        system_prompt = """You are a research report writer. Create a comprehensive, 
well-structured research report based on the findings from multiple research agents.

Your report should include:

1. **Executive Summary** (2-3 paragraphs)
   - Key findings
   - Main conclusions
   - Important implications

2. **Key Findings** (3-5 main findings)
   - Each finding with supporting evidence
   - Citations to sources where available [1], [2], etc.

3. **Data & Statistics** (if available)
   - Key metrics in a clear format
   - Trends and patterns

4. **Critical Analysis**
   - Limitations and caveats
   - Counterarguments considered
   - What remains uncertain

5. **Conclusions & Recommendations**
   - Summary of findings
   - Actionable recommendations if applicable
   - Areas for further research

6. **Sources**
   - Numbered list of all sources referenced

Write in a professional but accessible tone. Use markdown formatting.
Be comprehensive but avoid redundancy."""

        # Format context from all agents
        context_str = "## Research Findings from Specialist Agents\n\n"
        if context:
            for agent_name, output in context.items():
                if isinstance(output, dict):
                    content = output.get("content", str(output))
                    sources = output.get("sources", [])
                elif hasattr(output, "content"):
                    content = output.content
                    sources = getattr(output, "sources", [])
                else:
                    content = str(output)
                    sources = []
                
                context_str += f"### From {agent_name.title()} Agent:\n"
                context_str += f"{content[:3000]}\n"
                if sources:
                    context_str += f"Sources: {', '.join(sources[:5])}\n"
                context_str += "\n---\n\n"
        
        user_prompt = f"Research Question: {task}\n\n{context_str}"
        
        report = self._complete(system_prompt, user_prompt, temperature=0.4)
        
        # Add metadata footer
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        agents_used = list(context.keys()) if context else []
        
        report += f"\n\n---\n"
        report += f"*Generated by ResearchSwarm on {timestamp}*\n"
        if agents_used:
            report += f"*Agents used: {', '.join(agents_used)}*\n"
        
        return report
